package Main;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author mgbl2
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        JWelcome = new javax.swing.JLabel();
        JUsername = new javax.swing.JLabel();
        jMainLogo = new javax.swing.JLabel();
        JUsername_TextField = new javax.swing.JTextField();
        JPassword = new javax.swing.JLabel();
        JShowCheckbox = new javax.swing.JCheckBox();
        JPassword_TextField = new javax.swing.JPasswordField();
        JMinimized = new javax.swing.JLabel();
        JClose = new javax.swing.JLabel();
        JLogin_Button = new javax.swing.JLabel();
        JReset_Button = new javax.swing.JLabel();
        DragLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(500, 550));
        setResizable(false);

        kGradientPanel1.setkEndColor(new java.awt.Color(255, 215, 0));
        kGradientPanel1.setkStartColor(new java.awt.Color(128, 0, 0));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JWelcome.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        JWelcome.setForeground(new java.awt.Color(255, 255, 255));
        JWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JWelcome.setText("WELCOME!");
        kGradientPanel1.add(JWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 500, -1));

        JUsername.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        JUsername.setForeground(new java.awt.Color(255, 255, 255));
        JUsername.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N
        JUsername.setText("Username");
        kGradientPanel1.add(JUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 110, 30));

        jMainLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMainLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Main Logo.png"))); // NOI18N
        kGradientPanel1.add(jMainLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 500, 210));

        JUsername_TextField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        JUsername_TextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        JUsername_TextField.setSelectionColor(new java.awt.Color(128, 0, 0));
        kGradientPanel1.add(JUsername_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 210, 30));

        JPassword.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        JPassword.setForeground(new java.awt.Color(255, 255, 255));
        JPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pass.png"))); // NOI18N
        JPassword.setText("Password");
        kGradientPanel1.add(JPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 110, 30));

        JShowCheckbox.setText("Show");
        JShowCheckbox.setBorder(null);
        JShowCheckbox.setContentAreaFilled(false);
        JShowCheckbox.setFocusPainted(false);
        JShowCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JShowCheckboxActionPerformed(evt);
            }
        });
        kGradientPanel1.add(JShowCheckbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 420, -1, 30));

        JPassword_TextField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        JPassword_TextField.setSelectionColor(new java.awt.Color(128, 0, 0));
        kGradientPanel1.add(JPassword_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 420, 210, 30));

        JMinimized.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/minimized.png"))); // NOI18N
        JMinimized.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JMinimized.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JMinimizedMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JMinimizedMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JMinimizedMouseExited(evt);
            }
        });
        kGradientPanel1.add(JMinimized, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, -1, -1));

        JClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        JClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JCloseMouseExited(evt);
            }
        });
        kGradientPanel1.add(JClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, -1, -1));

        JLogin_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login-button.png"))); // NOI18N
        JLogin_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JLogin_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLogin_ButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JLogin_ButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JLogin_ButtonMouseExited(evt);
            }
        });
        kGradientPanel1.add(JLogin_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, -1, -1));

        JReset_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reset-button.png"))); // NOI18N
        JReset_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JReset_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JReset_ButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JReset_ButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JReset_ButtonMouseExited(evt);
            }
        });
        kGradientPanel1.add(JReset_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 480, -1, -1));

        DragLabel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                DragLabelMouseDragged(evt);
            }
        });
        kGradientPanel1.add(DragLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JShowCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JShowCheckboxActionPerformed
        // TODO add your handling code here:
        
        if(JShowCheckbox.isSelected()){
            JPassword_TextField.setEchoChar((char)0);
        }
        else{
            JPassword_TextField.setEchoChar('*');
        }
    }//GEN-LAST:event_JShowCheckboxActionPerformed

    private void JCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JCloseMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_JCloseMouseClicked

    private void JMinimizedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JMinimizedMouseClicked
        // TODO add your handling code here:
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_JMinimizedMouseClicked

    private void JCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JCloseMouseEntered
        // TODO add your handling code here:
        JClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close-hover.png")));
    }//GEN-LAST:event_JCloseMouseEntered

    private void JMinimizedMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JMinimizedMouseEntered
        // TODO add your handling code here:
        JMinimized.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/minimized-hover.png")));
    }//GEN-LAST:event_JMinimizedMouseEntered

    private void JMinimizedMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JMinimizedMouseExited
        // TODO add your handling code here:
        JMinimized.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/minimized.png")));
    }//GEN-LAST:event_JMinimizedMouseExited

    private void JCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JCloseMouseExited
        // TODO add your handling code here:
        JClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png")));
    }//GEN-LAST:event_JCloseMouseExited

    private void JLogin_ButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLogin_ButtonMouseEntered
        // TODO add your handling code here:
        JLogin_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login-button-hover.png")));
    }//GEN-LAST:event_JLogin_ButtonMouseEntered

    private void JLogin_ButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLogin_ButtonMouseExited
        // TODO add your handling code here:
        JLogin_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login-button.png")));
    }//GEN-LAST:event_JLogin_ButtonMouseExited

    private void JReset_ButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JReset_ButtonMouseEntered
        // TODO add your handling code here:
        JReset_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reset-button-hover.png")));
    }//GEN-LAST:event_JReset_ButtonMouseEntered

    private void JReset_ButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JReset_ButtonMouseExited
        // TODO add your handling code here:
        JReset_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reset-button.png")));
    }//GEN-LAST:event_JReset_ButtonMouseExited

    private void JLogin_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLogin_ButtonMouseClicked
        // TODO add your handling code here:
        String username = "user";
        String password = "1234";
        
        String userfield = JUsername_TextField.getText();
        String passfield = JPassword_TextField.getText();
        
        if(userfield.length()==0 || passfield.length()==0){
            JOptionPane.showMessageDialog(null,"Please don't leave the textfield blank","Warning",JOptionPane.WARNING_MESSAGE);
        }
        else if(userfield.equals(username) && passfield.equals(password)){
            JOptionPane.showMessageDialog(null, "Log in successfully!","Log In Success",JOptionPane.INFORMATION_MESSAGE);
            this.setVisible(false);
            new Main().setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(null,"Invalid Username or Password!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_JLogin_ButtonMouseClicked

    private void JReset_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JReset_ButtonMouseClicked
        // TODO add your handling code here:
        String clear = "";
        
        JUsername_TextField.setText(clear);
        JPassword_TextField.setText(clear);
    }//GEN-LAST:event_JReset_ButtonMouseClicked

    private void DragLabelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DragLabelMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x, y);
    }//GEN-LAST:event_DragLabelMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DragLabel;
    private javax.swing.JLabel JClose;
    private javax.swing.JLabel JLogin_Button;
    private javax.swing.JLabel JMinimized;
    private javax.swing.JLabel JPassword;
    private javax.swing.JPasswordField JPassword_TextField;
    private javax.swing.JLabel JReset_Button;
    private javax.swing.JCheckBox JShowCheckbox;
    private javax.swing.JLabel JUsername;
    private javax.swing.JTextField JUsername_TextField;
    private javax.swing.JLabel JWelcome;
    private javax.swing.JLabel jMainLogo;
    private keeptoo.KGradientPanel kGradientPanel1;
    // End of variables declaration//GEN-END:variables
}
