/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;

/**
 *
 * @author mgbl2
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        JMinimized = new javax.swing.JLabel();
        JClose = new javax.swing.JLabel();
        HeaderPanel = new javax.swing.JPanel();
        Header = new javax.swing.JLabel();
        DateOfBirth = new javax.swing.JLabel();
        StudentIDTextField = new javax.swing.JTextField();
        Header3 = new javax.swing.JLabel();
        LastNameTextField = new javax.swing.JTextField();
        Header4 = new javax.swing.JLabel();
        Header5 = new javax.swing.JLabel();
        StudentID = new javax.swing.JLabel();
        FirstNameTextField = new javax.swing.JTextField();
        MiddleNameTextField = new javax.swing.JTextField();
        FullName = new javax.swing.JLabel();
        YearLevelComboBox = new javax.swing.JComboBox<>();
        YearLevel = new javax.swing.JLabel();
        DateOfBirthComboBox = new com.toedter.calendar.JDateChooser();
        Gender = new javax.swing.JLabel();
        GenderComboBox = new javax.swing.JComboBox<>();
        Department = new javax.swing.JLabel();
        DepartmentComboBox = new javax.swing.JComboBox<>();
        Programs = new javax.swing.JLabel();
        ProgramsComboBox = new javax.swing.JComboBox<>();
        SaveButton = new javax.swing.JLabel();
        UpdateButton = new javax.swing.JLabel();
        DeleteButton = new javax.swing.JLabel();
        ResetButton = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        PersonalInfomation = new javax.swing.JLabel();
        Divider = new javax.swing.JPanel();
        DragLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        StudentID1 = new javax.swing.JLabel();
        StudentIDTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1530, 760));
        setResizable(false);

        kGradientPanel1.setkEndColor(new java.awt.Color(255, 215, 0));
        kGradientPanel1.setkGradientFocus(1000);
        kGradientPanel1.setkStartColor(new java.awt.Color(128, 0, 0));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JMinimized.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/minimized.png"))); // NOI18N
        JMinimized.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JMinimized.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JMinimizedMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JMinimizedMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JMinimizedMouseExited(evt);
            }
        });
        kGradientPanel1.add(JMinimized, new org.netbeans.lib.awtextra.AbsoluteConstraints(1470, 10, -1, -1));

        JClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        JClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JCloseMouseExited(evt);
            }
        });
        kGradientPanel1.add(JClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1500, 10, -1, -1));

        HeaderPanel.setBackground(new java.awt.Color(255, 215, 0));
        HeaderPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        HeaderPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Header.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        Header.setForeground(new java.awt.Color(128, 0, 0));
        Header.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Header.setText("Student Registration System");
        HeaderPanel.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1520, 60));

        kGradientPanel1.add(HeaderPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1540, 60));

        DateOfBirth.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        DateOfBirth.setForeground(new java.awt.Color(255, 215, 0));
        DateOfBirth.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        DateOfBirth.setText("Date of Birth");
        kGradientPanel1.add(DateOfBirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 110, 20));

        StudentIDTextField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        kGradientPanel1.add(StudentIDTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 110, 170, 20));

        Header3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Header3.setForeground(new java.awt.Color(255, 215, 0));
        Header3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Header3.setText("First Name");
        kGradientPanel1.add(Header3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 100, 20));

        LastNameTextField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        kGradientPanel1.add(LastNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 110, 30));

        Header4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Header4.setForeground(new java.awt.Color(255, 215, 0));
        Header4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Header4.setText("Middle Name");
        kGradientPanel1.add(Header4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 110, 20));

        Header5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Header5.setForeground(new java.awt.Color(255, 215, 0));
        Header5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Header5.setText("Last Name");
        kGradientPanel1.add(Header5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 110, 20));

        StudentID.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        StudentID.setForeground(new java.awt.Color(255, 215, 0));
        StudentID.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        StudentID.setText("Search");
        kGradientPanel1.add(StudentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 110, -1, 20));

        FirstNameTextField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        kGradientPanel1.add(FirstNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 100, 30));

        MiddleNameTextField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        kGradientPanel1.add(MiddleNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 110, 30));

        FullName.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        FullName.setForeground(new java.awt.Color(255, 215, 0));
        FullName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        FullName.setText("Full Name");
        kGradientPanel1.add(FullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 130, 20));

        YearLevelComboBox.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        YearLevelComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1st Year", "2nd Year", "3rd Year", "4th Year" }));
        YearLevelComboBox.setBorder(null);
        kGradientPanel1.add(YearLevelComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, -1, 30));

        YearLevel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        YearLevel.setForeground(new java.awt.Color(255, 215, 0));
        YearLevel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        YearLevel.setText("Year Level");
        kGradientPanel1.add(YearLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 100, 20));
        kGradientPanel1.add(DateOfBirthComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 110, 30));

        Gender.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Gender.setForeground(new java.awt.Color(255, 215, 0));
        Gender.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Gender.setText("Gender");
        kGradientPanel1.add(Gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 70, 20));

        GenderComboBox.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        GenderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        GenderComboBox.setBorder(null);
        kGradientPanel1.add(GenderComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, 30));

        Department.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Department.setForeground(new java.awt.Color(255, 215, 0));
        Department.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Department.setText("Department");
        kGradientPanel1.add(Department, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, 110, 20));

        DepartmentComboBox.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        DepartmentComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PROFESSIONAL SCHOOLS", "COLLEGE OF ACOUNTING EDUCATION", "COLLEGE OF ARCHITECTURE & FINE ARTS EDUCATION", "COLLEGE OF ARTS AND SCIENCE EDUCATION", "COLLEGE OF BUSINESS ADMINISTRATION", "COLLEGE OF COMPUTING EDUCATION", "COLLEGE OF CRIMINAL JUSTICE EDUCATION" }));
        DepartmentComboBox.setBorder(null);
        kGradientPanel1.add(DepartmentComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 480, 340, 30));

        Programs.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Programs.setForeground(new java.awt.Color(255, 215, 0));
        Programs.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Programs.setText("Programs");
        kGradientPanel1.add(Programs, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 110, 30));

        ProgramsComboBox.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        ProgramsComboBox.setBorder(null);
        kGradientPanel1.add(ProgramsComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, 270, 30));

        SaveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save-button.png"))); // NOI18N
        SaveButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SaveButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SaveButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SaveButtonMouseExited(evt);
            }
        });
        kGradientPanel1.add(SaveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 680, -1, -1));

        UpdateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update-button.png"))); // NOI18N
        UpdateButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        UpdateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                UpdateButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                UpdateButtonMouseExited(evt);
            }
        });
        kGradientPanel1.add(UpdateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 680, -1, -1));

        DeleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete-button.png"))); // NOI18N
        DeleteButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DeleteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DeleteButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DeleteButtonMouseExited(evt);
            }
        });
        kGradientPanel1.add(DeleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 680, -1, -1));

        ResetButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/main-reset-button.png"))); // NOI18N
        ResetButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ResetButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ResetButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ResetButtonMouseExited(evt);
            }
        });
        kGradientPanel1.add(ResetButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 680, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "FIRST NAME", "MIDDLE NAME", "LAST NAME", "GENDER", "DATE OF BIRTH", "YEAR LEVEL", "DEPARTMENT", "PROGRAM"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
            jTable1.getColumnModel().getColumn(6).setResizable(false);
            jTable1.getColumnModel().getColumn(7).setResizable(false);
            jTable1.getColumnModel().getColumn(8).setResizable(false);
        }

        kGradientPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, 920, 610));

        PersonalInfomation.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        PersonalInfomation.setForeground(new java.awt.Color(255, 215, 0));
        PersonalInfomation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PersonalInfomation.setText("Personal Information");
        kGradientPanel1.add(PersonalInfomation, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 250, 20));

        Divider.setBackground(new java.awt.Color(255, 217, 0));
        Divider.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout DividerLayout = new javax.swing.GroupLayout(Divider);
        Divider.setLayout(DividerLayout);
        DividerLayout.setHorizontalGroup(
            DividerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        DividerLayout.setVerticalGroup(
            DividerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        kGradientPanel1.add(Divider, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, 10, 670));

        DragLabel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                DragLabelMouseDragged(evt);
            }
        });
        kGradientPanel1.add(DragLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1460, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/export-button.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });
        kGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 110, 90, -1));

        StudentID1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        StudentID1.setForeground(new java.awt.Color(255, 215, 0));
        StudentID1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        StudentID1.setText("Student ID");
        kGradientPanel1.add(StudentID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, 20));

        StudentIDTextField1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        kGradientPanel1.add(StudentIDTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 170, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JMinimizedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JMinimizedMouseClicked
        // TODO add your handling code here:
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_JMinimizedMouseClicked

    private void JMinimizedMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JMinimizedMouseEntered
        // TODO add your handling code here:
        JMinimized.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/minimized-hover.png")));
    }//GEN-LAST:event_JMinimizedMouseEntered

    private void JMinimizedMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JMinimizedMouseExited
        // TODO add your handling code here:
        JMinimized.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/minimized.png")));
    }//GEN-LAST:event_JMinimizedMouseExited

    private void JCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JCloseMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_JCloseMouseClicked

    private void JCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JCloseMouseEntered
        // TODO add your handling code here:
        JClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close-hover.png")));
    }//GEN-LAST:event_JCloseMouseEntered

    private void JCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JCloseMouseExited
        // TODO add your handling code here:
        JClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png")));
    }//GEN-LAST:event_JCloseMouseExited

    private void SaveButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaveButtonMouseEntered
        // TODO add your handling code here:
        SaveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save-button-hover.png")));
    }//GEN-LAST:event_SaveButtonMouseEntered

    private void SaveButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaveButtonMouseExited
        // TODO add your handling code here:
        SaveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save-button.png")));
    }//GEN-LAST:event_SaveButtonMouseExited

    private void UpdateButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateButtonMouseEntered
        // TODO add your handling code here:
        UpdateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update-button-hover.png")));
    }//GEN-LAST:event_UpdateButtonMouseEntered

    private void UpdateButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateButtonMouseExited
        // TODO add your handling code here:
        UpdateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update-button.png")));
    }//GEN-LAST:event_UpdateButtonMouseExited

    private void DeleteButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteButtonMouseEntered
        // TODO add your handling code here:
        DeleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete-button-hover.png")));
    }//GEN-LAST:event_DeleteButtonMouseEntered

    private void DeleteButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteButtonMouseExited
        // TODO add your handling code here:
        DeleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete-button.png")));
    }//GEN-LAST:event_DeleteButtonMouseExited

    private void ResetButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResetButtonMouseEntered
        // TODO add your handling code here:
        ResetButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/main-reset-button-hover.png")));
    }//GEN-LAST:event_ResetButtonMouseEntered

    private void ResetButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResetButtonMouseExited
        // TODO add your handling code here:
        ResetButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/main-reset-button.png")));
    }//GEN-LAST:event_ResetButtonMouseExited

    private void DragLabelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DragLabelMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x, y);
    }//GEN-LAST:event_DragLabelMouseDragged

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        // TODO add your handling code here:
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/export-button-hover.png")));
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        // TODO add your handling code here:
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/export-button.png")));
    }//GEN-LAST:event_jLabel1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DateOfBirth;
    private com.toedter.calendar.JDateChooser DateOfBirthComboBox;
    private javax.swing.JLabel DeleteButton;
    private javax.swing.JLabel Department;
    private javax.swing.JComboBox<String> DepartmentComboBox;
    private javax.swing.JPanel Divider;
    private javax.swing.JLabel DragLabel;
    private javax.swing.JTextField FirstNameTextField;
    private javax.swing.JLabel FullName;
    private javax.swing.JLabel Gender;
    private javax.swing.JComboBox<String> GenderComboBox;
    private javax.swing.JLabel Header;
    private javax.swing.JLabel Header3;
    private javax.swing.JLabel Header4;
    private javax.swing.JLabel Header5;
    private javax.swing.JPanel HeaderPanel;
    private javax.swing.JLabel JClose;
    private javax.swing.JLabel JMinimized;
    private javax.swing.JTextField LastNameTextField;
    private javax.swing.JTextField MiddleNameTextField;
    private javax.swing.JLabel PersonalInfomation;
    private javax.swing.JLabel Programs;
    private javax.swing.JComboBox<String> ProgramsComboBox;
    private javax.swing.JLabel ResetButton;
    private javax.swing.JLabel SaveButton;
    private javax.swing.JLabel StudentID;
    private javax.swing.JLabel StudentID1;
    private javax.swing.JTextField StudentIDTextField;
    private javax.swing.JTextField StudentIDTextField1;
    private javax.swing.JLabel UpdateButton;
    private javax.swing.JLabel YearLevel;
    private javax.swing.JComboBox<String> YearLevelComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private keeptoo.KGradientPanel kGradientPanel1;
    // End of variables declaration//GEN-END:variables
}
